version: "3"

services:

  node3-zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: node3-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  node2-kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: node2-kafka
    depends_on:
      - node3-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: node3-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://node2-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  node1-spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: node1-spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      INIT_DAEMON_STEP: setup_spark